# The following environment variables are substituted if present
# * QUORUM_CONSENSUS: default to istanbul
# * QUORUM_DOCKER_IMAGE: default to quorumengineering/quorum:2.1.1
# * QUORUM_TX_MANAGER_DOCKER_IMAGE: default to quorumengineering/tessera:0.7.3
# To use Constellation, set QUORUM_TX_MANAGER_DOCKER_IMAGE to Constellation docker image,
# e.g.: QUORUM_TX_MANAGER_DOCKER_IMAGE=quorumengineering/constellation:0.3.2 docker-compose up -d
version: "3.7"
x-quorum-def:
  &quorum-def
  restart: "on-failure"
  image: "${QUORUM_DOCKER_IMAGE:-quorumengineering/quorum:2.1.1}"
  expose:
  - "21000"
  - "50400"
  healthcheck:
    test: ["CMD", "wget", "--spider", "http://localhost:8545"]
    interval: 3s
    timeout: 3s
    retries: 10
    start_period: 5s
  labels:
    com.quorum.consensus: ${QUORUM_CONSENSUS:-istanbul}
  entrypoint:
  - /bin/sh
  - -c
  - |
    DDIR=/qdata/dd
    rm -rf $${DDIR}
    mkdir -p $${DDIR}/keystore
    mkdir -p $${DDIR}/geth
    cp /examples/raft/nodekey$${NODE_ID} $${DDIR}/geth/nodekey
    cp /examples/keys/key$${NODE_ID} $${DDIR}/keystore/
    cat /examples/permissioned-nodes.json | sed 's/^\(.*\)@.*\?\(.*\)raftport=5040\([0-9]\)\(.*\)$$/\1@172.16.239.1\3:21000?discport=0\&raftport=50400\4/g' > $${DDIR}/static-nodes.json
    cp $${DDIR}/static-nodes.json $${DDIR}/permissioned-nodes.json
    cat $${DDIR}/static-nodes.json
    GENESIS_FILE="/examples/istanbul-genesis.json"
    if [ "${QUORUM_CONSENSUS:-istanbul}" == "raft" ]; then
      GENESIS_FILE="/examples/genesis.json"
    fi
    NETWORK_ID=$$(cat $${GENESIS_FILE} | grep chainId | awk -F " " '{print $$2}' | awk -F "," '{print $$1}')
    GETH_ARGS_raft="--raft --raftport 50400"
    GETH_ARGS_istanbul="--emitcheckpoints --istanbul.blockperiod 1 --mine --minerthreads 1 --syncmode full"
    geth --datadir $${DDIR} init $${GENESIS_FILE}
    geth \
      --identity node$${NODE_ID}-${QUORUM_CONSENSUS:-istanbul} \
      --datadir $${DDIR} \
      --permissioned \
      --nodiscover \
      --verbosity 5 \
      --networkid $${NETWORK_ID} \
      --rpc \
      --rpcaddr 0.0.0.0 \
      --rpcport 8545 \
      --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,${QUORUM_CONSENSUS:-istanbul} \
      --port 21000 \
      --unlock 0 \
      --password /examples/passwords.txt \
      $${GETH_ARGS_${QUORUM_CONSENSUS:-istanbul}}

services:
  node1:
    << : *quorum-def
    hostname: node1
    ports:
    - "22000:8545"
    volumes:
    - 1:/qdata
    - ./examples/7nodes:/examples:ro

    environment:
    - PRIVATE_CONFIG=/qdata/tm/tm.ipc
    - NODE_ID=1
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.11

  node2:
    << : *quorum-def
    hostname: node2
    ports:
    - "22001:8545"
    volumes:
    - 2:/qdata
    - ./examples/7nodes:/examples:ro

    environment:
    - PRIVATE_CONFIG=/qdata/tm/tm.ipc
    - NODE_ID=2
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.12

  node3:
    << : *quorum-def
    hostname: node3
    ports:
    - "22002:8545"
    volumes:
    - 3:/qdata
    - ./examples/7nodes:/examples:ro

    environment:
    - PRIVATE_CONFIG=/qdata/tm/tm.ipc
    - NODE_ID=3
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.13

  node4:
    << : *quorum-def
    hostname: node4
    ports:
    - "22003:8545"
    volumes:
    - 4:/qdata
    - ./examples/7nodes:/examples:ro

    environment:
    - PRIVATE_CONFIG=/qdata/tm/tm.ipc
    - NODE_ID=4
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.14

networks:
  quorum-examples-net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24
volumes:
  "1":
  "2":
  "3":
  "4":
